# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a99ed76208df4d6ba355bf618c34f25eceb80568d2ed217b246cc7e29f68be5b7770f89700998709ab0f578a66f43f2b537a8c7cde99793e843b3a0d734a9fb

test:
  secret_key_base: 66e215a8d022c617d47a5e447bb520d01896aff057f007a7f87287703c9c5983806949efdcb734f5ada2d9d6d767c1d72379c36b79422f475b34690f3e778fac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
